#!/bin/bash

DOCKER_REPO="mschmoock/tor-sshd"
VERSION=$(cat VERSION)
echo "Tagging and pushing..."

docker tag $DOCKER_REPO:$VERSION $DOCKER_REPO:latest

docker push $DOCKER_REPO
docker push $DOCKER_REPO:$VERSION
